plugins {
    id 'com.android.library'
}
repositories {
    mavenCentral()
    google() // Needed for androidx
    maven{ url = 'https://www.jitpack.io'}
    maven{ url = 'https://maven.brott.dev/'}

}

android {
    namespace 'com.example.chassi'

    // Usa as mesmas configurações da SDK FTC
    compileSdk 30

    defaultConfig {
        minSdk 24
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

// 🔹 Importa o mesmo arquivo de dependências usado pelos outros módulos
apply from: '../build.dependencies.gradle'

dependencies {

    implementation 'com.acmerobotics.roadrunner:ftc:0.1.25'
    implementation 'com.acmerobotics.roadrunner:core:1.0.1'
    implementation 'com.acmerobotics.roadrunner:actions:1.0.1'
    implementation 'com.acmerobotics.dashboard:dashboard:0.5.1'

    // Opcional: se você quiser usar classes do FtcRobotController
    implementation project(':FtcRobotController')
    implementation project(':Constants')
}
